#!/usr/bin/env python3
"""
RedditHarbor Opportunity Dashboard

Interactive dashboard showing AI-powered app opportunities from Reddit data.
"""

import marimo as mo
from supabase import create_client
import os

# Initialize Supabase client
supabase = create_client(
    os.getenv('SUPABASE_URL'),
    os.getenv('SUPABASE_KEY')
)

app = mo.App()

# Cell 1: Header
@app.cell
def _():
    mo.md("# 🎯 RedditHarbor - App Opportunity Discovery")
    return

# Cell 2: Description
@app.cell
def _():
    mo.md("""
    ## AI-Powered App Ideas from Reddit

    This dashboard displays app development opportunities identified through:
    1. Reddit data collection from high-signal subreddits
    2. AI analysis using Claude Haiku via OpenRouter
    3. Multi-dimensional scoring (Market, Pain, Monetization, Feasibility)

    **Showing opportunities with score >= 40.0**
    """)
    return

# Cell 3: Fetch data
@app.cell
def _():
    # Fetch opportunities data from app_opportunities table
    result = supabase.table('app_opportunities').select(
        'submission_id, opportunity_score, problem_description, app_concept, core_functions, target_user, subreddit, title'
    ).gte('opportunity_score', 40.0).order('opportunity_score', desc=True).execute()

    data = result.data
    return data

# Cell 4: Table
@app.cell
def _(data):
    if not data:
        mo.md("No opportunities found with score >= 40.0")
    else:
        # Convert to display format
        display_data = []
        for opp in data:
            functions = opp.get('core_functions', [])
            if isinstance(functions, str):
                try:
                    functions = eval(functions)
                except:
                    functions = [functions]

            display_data.append({
                'Score': f"{opp.get('opportunity_score', 0):.1f}",
                'Subreddit': opp.get('subreddit', 'N/A'),
                'Problem': opp.get('problem_description', 'N/A')[:60] + "...",
                'App Concept': opp.get('app_concept', 'N/A')[:60] + "...",
                'Target': opp.get('target_user', 'N/A')[:30],
                'Functions': f"{len(functions)}"
            })

        mo.ui.table(display_data, label=f"Top {len(display_data)} Opportunities")
    return

# Cell 5: Stats
@app.cell
def _(data):
    total = len(data)
    avg_score = sum(opp.get('opportunity_score', 0) for opp in data) / total if total > 0 else 0
    high_score_count = len([o for o in data if o.get('opportunity_score', 0) >= 45])

    mo.md(f"""
    ## Summary

    - **Total Opportunities:** {total}
    - **Average Score:** {avg_score:.1f}
    - **High-Score (≥45):** {high_score_count}
    """)
    return

# Cell 6: Footer
@app.cell
def _():
    mo.md("---")
    mo.md("*Generated by RedditHarbor - AI-Powered App Discovery*")
    return

if __name__ == "__main__":
    app.run()
