#!/usr/bin/env python3
"""
RedditHarbor Opportunity Dashboard - Reactive Version

Displays AI-generated app opportunities from Reddit.
"""

import marimo

__generated_with = "0.17.6"
app = marimo.App()


@app.cell
def __():
    import marimo as mo
    from supabase import create_client
    import os
    return mo, create_client, os


@app.cell
def __(create_client, os):
    supabase = create_client(
        os.getenv('SUPABASE_URL', 'http://127.0.0.1:54321'),
        os.getenv('SUPABASE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU')
    )
    return supabase,


@app.cell
def __(mo):
    mo.md("# 🎯 RedditHarbor - App Opportunity Discovery")
    return


@app.cell
def __(mo):
    mo.md("""
    ## AI-Powered App Ideas from Reddit

    This dashboard displays app development opportunities identified through:
    1. Reddit data collection from high-signal subreddits
    2. AI analysis using Claude Haiku via OpenRouter
    3. Multi-dimensional scoring (Market, Pain, Monetization, Feasibility)

    **Showing opportunities with score >= 20.0**
    """)
    return


@app.cell
def __(supabase):
    # Fetch AI-generated opportunities
    result = supabase.table('app_opportunities').select(
        'submission_id, opportunity_score, problem_description, app_concept, core_functions, target_user, monetization_model, subreddit, title'
    ).gte('opportunity_score', 20.0).order('opportunity_score', desc=True).execute()

    opportunities = result.data if result.data else []
    return opportunities, result


@app.cell
def __(mo, opportunities):
    if not opportunities:
        mo.md("### No opportunities found with score >= 20.0")
    else:
        # Build table data
        table_data = []
        for opp in opportunities:
            functions = opp.get('core_functions', [])

            table_data.append({
                'Score': f"{opp.get('opportunity_score', 0):.1f}",
                'Subreddit': opp.get('subreddit', 'N/A') or 'N/A',
                'Problem': opp.get('problem_description', 'N/A')[:80] + "...",
                'App Concept': opp.get('app_concept', 'N/A')[:80] + "...",
                'Target': opp.get('target_user', 'N/A')[:40] + "...",
                'Functions': str(len(functions)) if isinstance(functions, list) else "1"
            })

        mo.ui.table(table_data, label=f"Top {len(table_data)} AI-Generated Opportunities")
    return opp, table_data


@app.cell
def __(mo, opportunities):
    total = len(opportunities)
    avg_score = sum(o.get('opportunity_score', 0) for o in opportunities) / total if total > 0 else 0
    high_score = len([o for o in opportunities if o.get('opportunity_score', 0) >= 45])

    mo.md(f"""
    ## Summary

    - **Total AI Profiles:** {total}
    - **Average Score:** {avg_score:.1f}
    - **High-Score (≥45):** {high_score}
    - **Cost per Profile:** ~$0.001 (Claude Haiku via OpenRouter)
    """)
    return avg_score, high_score, total


@app.cell
def __(mo):
    mo.md("---")
    mo.md("*Generated by RedditHarbor - AI-Powered App Discovery*")
    return


if __name__ == "__main__":
    app.run()
