#!/usr/bin/env python3
"""
RedditHarbor Opportunity Dashboard - FIXED

Interactive dashboard showing AI-powered app opportunities from Reddit data.
Fixed: Proper imports, correct table/column names, correct score threshold.
"""

import marimo

__generated_with = "0.17.6"
app = marimo.App()


@app.cell
def _():
    import marimo as mo
    from supabase import create_client
    import os

    supabase = create_client(
        os.getenv('SUPABASE_URL'),
        os.getenv('SUPABASE_KEY')
    )
    return mo, supabase


@app.cell
def _(mo):
    mo.md("""
    # 🎯 RedditHarbor - App Opportunity Discovery
    """)
    return


@app.cell
def _(mo):
    mo.md("""
    ## AI-Powered App Ideas from Reddit

    This dashboard displays app development opportunities identified through:
    1. Reddit data collection from high-signal subreddits
    2. AI analysis using Claude Haiku via OpenRouter
    3. Multi-dimensional scoring (Market, Pain, Monetization, Feasibility)

    **Showing opportunities with score >= 20.0**
    """)
    return


@app.cell
def _(supabase):
    # Fetch AI-generated opportunities from app_opportunities table
    result = supabase.table('app_opportunities').select(
        'submission_id, opportunity_score, problem_description, app_concept, core_functions, target_user, monetization_model, subreddit, title'
    ).gte('opportunity_score', 20.0).order('opportunity_score', desc=True).execute()

    data = result.data if result.data else []
    return (data,)


@app.cell
def _(data, mo):
    # Convert to display format
    if not data:
        output = mo.md("No opportunities found with score >= 20.0")
    else:
        display_data = []
        for opp in data:
            functions = opp.get('core_functions', [])
            if isinstance(functions, str):
                try:
                    functions = eval(functions)
                except:
                    functions = [str(functions)]

            display_data.append({
                'Score': f"{opp.get('opportunity_score', 0):.1f}",
                'Subreddit': opp.get('subreddit', 'N/A') or 'N/A',
                'Problem': opp.get('problem_description', 'N/A'),
                'App Concept': opp.get('app_concept', 'N/A'),
                'Target User': opp.get('target_user', 'N/A'),
                'Value Prop': opp.get('monetization_model', 'N/A'),
                'Functions': f"{len(functions)}" if isinstance(functions, list) else "1"
            })

        output = mo.ui.table(display_data, label=f"Top {len(display_data)} AI-Generated Opportunities")

    output
    return


@app.cell
def _(data, mo):
    total = len(data)
    avg_score = sum(opp.get('opportunity_score', 0) for opp in data) / total if total > 0 else 0
    high_score_count = len([o for o in data if o.get('opportunity_score', 0) >= 45])

    mo.md(f"""
    ## Summary

    - **Total AI Profiles:** {total}
    - **Average Score:** {avg_score:.1f}
    - **High-Score (≥45):** {high_score_count}
    - **Cost per Profile:** ~$0.001 (Claude Haiku via OpenRouter)
    """)
    return


@app.cell
def _(mo):
    mo.md("---")
    mo.md("*Generated by RedditHarbor - AI-Powered App Discovery*")
    return


if __name__ == "__main__":
    app.run()
