"""initial opportunity model

Revision ID: 54ff85914726
Revises:
Create Date: 2025-12-10 10:34:58.869694

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import inspect

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54ff85914726"
down_revision: str | Sequence[str] | None = None  # First real migration
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if opportunities table exists and rename it to opportunities_legacy
    conn = op.get_bind()
    inspector = inspect(conn)
    if "opportunities" in inspector.get_table_names():
        op.rename_table("opportunities", "opportunities_legacy")

    # Create new opportunities table based on SQLModel
    # Use PostgreSQL JSONB for better performance
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.String(), nullable=False),
        sa.Column("subreddit", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("wtp_score", sa.Float(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "analysis",
            sa.JSON().with_variant(sa.dialects.postgresql.JSONB, "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            sa.JSON().with_variant(sa.dialects.postgresql.JSONB, "postgresql"),
            nullable=False,
        ),
        sa.Column("trust_level", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        # Remove redundant UniqueConstraint - unique index is sufficient
        schema="public",
    )

    # Create indexes
    op.create_index(
        op.f("ix_opportunities_submission_id"),
        "opportunities",
        ["submission_id"],
        unique=True,
    )
    op.create_index(op.f("ix_opportunities_subreddit"), "opportunities", ["subreddit"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Note: This migration preserves data in the opportunities_legacy table.
    Data from the new opportunities table will be lost when downgrading.
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes
    op.drop_index(op.f("ix_opportunities_subreddit"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_submission_id"), table_name="opportunities")

    # Drop new opportunities table
    op.drop_table("opportunities", schema="public")

    # Check if opportunities_legacy exists and rename it back to opportunities
    conn = op.get_bind()
    inspector = inspect(conn)
    if "opportunities_legacy" in inspector.get_table_names():
        op.rename_table("opportunities_legacy", "opportunities")

    # ### end Alembic commands ###
